apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-nginx-webapp
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 4 # Starting with 2 replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-webapp
        image: ashish2706/argo-nginx-webapp:latest
        ports:
        - containerPort: 80
